apiVersion: monitoring.coreos.com/v1
kind: Prometheus
metadata:
  name: prometheus
  labels:
    app: prometheus
spec:
  image: quay.io/prometheus/prometheus:v2.53.0 
  nodeSelector:
    kubernetes.io/os: linux
  replicas: 1
  resources:
    requests:
      memory: 400Mi
  securityContext:
    fsGroup: 2000
    runAsNonRoot: true
    runAsUser: 1000
  serviceAccountName: prometheus
  version: v2.53.0
  serviceMonitorSelector: {}
  remoteWrite:
  - url: http://localhost:3000
    basicAuth:
      username:
        name: grafana-secret
        key: username
      password:
        name: grafana-secret
        key: password